
- id: json-schema-for-humans-md
  args: []
  description: Uses json-schema-for-humans to generate docs for JSON schema.
  types:
    - text
    - file
  entry: git-hooks/generate-schema-doc-md.sh
  files: \.schema\.json$
  language: python
  name: Generate Markdown from JSON schema
